//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Italia.Voucher18App.VerificaVoucher {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://bonus.mibact.it/VerificaVoucher/", ConfigurationName="VerificaVoucher.VerificaVoucher")]
    public interface VerificaVoucher {
        
        // CODEGEN: Generating message contract since the wrapper name (CheckRequestObj) of message CheckRequest does not match the default value (Check)
        [System.ServiceModel.OperationContractAttribute(Action="http://bonus.mibact.it/VerificaVoucher/Check", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Italia.Voucher18App.VerificaVoucher.CheckResponse1 Check(Italia.Voucher18App.VerificaVoucher.CheckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bonus.mibact.it/VerificaVoucher/Check", ReplyAction="*")]
        System.Threading.Tasks.Task<Italia.Voucher18App.VerificaVoucher.CheckResponse1> CheckAsync(Italia.Voucher18App.VerificaVoucher.CheckRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConfirmRequestObj) of message ConfirmRequest does not match the default value (Confirm)
        [System.ServiceModel.OperationContractAttribute(Action="http://bonus.mibact.it/VerificaVoucher/Confirm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Italia.Voucher18App.VerificaVoucher.ConfirmResponse1 Confirm(Italia.Voucher18App.VerificaVoucher.ConfirmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://bonus.mibact.it/VerificaVoucher/Confirm", ReplyAction="*")]
        System.Threading.Tasks.Task<Italia.Voucher18App.VerificaVoucher.ConfirmResponse1> ConfirmAsync(Italia.Voucher18App.VerificaVoucher.ConfirmRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bonus.mibact.it/VerificaVoucher/")]
    public partial class Check : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoOperazioneField;
        
        private string codiceVoucherField;
        
        private string partitaIvaEsercenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipoOperazione {
            get {
                return this.tipoOperazioneField;
            }
            set {
                this.tipoOperazioneField = value;
                this.RaisePropertyChanged("tipoOperazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codiceVoucher {
            get {
                return this.codiceVoucherField;
            }
            set {
                this.codiceVoucherField = value;
                this.RaisePropertyChanged("codiceVoucher");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string partitaIvaEsercente {
            get {
                return this.partitaIvaEsercenteField;
            }
            set {
                this.partitaIvaEsercenteField = value;
                this.RaisePropertyChanged("partitaIvaEsercente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bonus.mibact.it/VerificaVoucher/")]
    public partial class ConfirmResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string esitoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string esito {
            get {
                return this.esitoField;
            }
            set {
                this.esitoField = value;
                this.RaisePropertyChanged("esito");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bonus.mibact.it/VerificaVoucher/")]
    public partial class Confirm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoOperazioneField;
        
        private string codiceVoucherField;
        
        private double importoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipoOperazione {
            get {
                return this.tipoOperazioneField;
            }
            set {
                this.tipoOperazioneField = value;
                this.RaisePropertyChanged("tipoOperazione");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codiceVoucher {
            get {
                return this.codiceVoucherField;
            }
            set {
                this.codiceVoucherField = value;
                this.RaisePropertyChanged("codiceVoucher");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double importo {
            get {
                return this.importoField;
            }
            set {
                this.importoField = value;
                this.RaisePropertyChanged("importo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bonus.mibact.it/VerificaVoucher/")]
    public partial class CheckResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nominativoBeneficiarioField;
        
        private string partitaIvaEsercenteField;
        
        private string ambitoField;
        
        private string beneField;
        
        private double importoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string nominativoBeneficiario {
            get {
                return this.nominativoBeneficiarioField;
            }
            set {
                this.nominativoBeneficiarioField = value;
                this.RaisePropertyChanged("nominativoBeneficiario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string partitaIvaEsercente {
            get {
                return this.partitaIvaEsercenteField;
            }
            set {
                this.partitaIvaEsercenteField = value;
                this.RaisePropertyChanged("partitaIvaEsercente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ambito {
            get {
                return this.ambitoField;
            }
            set {
                this.ambitoField = value;
                this.RaisePropertyChanged("ambito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string bene {
            get {
                return this.beneField;
            }
            set {
                this.beneField = value;
                this.RaisePropertyChanged("bene");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double importo {
            get {
                return this.importoField;
            }
            set {
                this.importoField = value;
                this.RaisePropertyChanged("importo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckRequestObj", WrapperNamespace="http://bonus.mibact.it/VerificaVoucher/", IsWrapped=true)]
    public partial class CheckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bonus.mibact.it/VerificaVoucher/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Italia.Voucher18App.VerificaVoucher.Check checkReq;
        
        public CheckRequest() {
        }
        
        public CheckRequest(Italia.Voucher18App.VerificaVoucher.Check checkReq) {
            this.checkReq = checkReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CheckResponseObj", WrapperNamespace="http://bonus.mibact.it/VerificaVoucher/", IsWrapped=true)]
    public partial class CheckResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bonus.mibact.it/VerificaVoucher/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Italia.Voucher18App.VerificaVoucher.CheckResponse checkResp;
        
        public CheckResponse1() {
        }
        
        public CheckResponse1(Italia.Voucher18App.VerificaVoucher.CheckResponse checkResp) {
            this.checkResp = checkResp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmRequestObj", WrapperNamespace="http://bonus.mibact.it/VerificaVoucher/", IsWrapped=true)]
    public partial class ConfirmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bonus.mibact.it/VerificaVoucher/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Italia.Voucher18App.VerificaVoucher.Confirm checkReq;
        
        public ConfirmRequest() {
        }
        
        public ConfirmRequest(Italia.Voucher18App.VerificaVoucher.Confirm checkReq) {
            this.checkReq = checkReq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConfirmResponseObj", WrapperNamespace="http://bonus.mibact.it/VerificaVoucher/", IsWrapped=true)]
    public partial class ConfirmResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://bonus.mibact.it/VerificaVoucher/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Italia.Voucher18App.VerificaVoucher.ConfirmResponse checkResp;
        
        public ConfirmResponse1() {
        }
        
        public ConfirmResponse1(Italia.Voucher18App.VerificaVoucher.ConfirmResponse checkResp) {
            this.checkResp = checkResp;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VerificaVoucherChannel : Italia.Voucher18App.VerificaVoucher.VerificaVoucher, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VerificaVoucherClient : System.ServiceModel.ClientBase<Italia.Voucher18App.VerificaVoucher.VerificaVoucher>, Italia.Voucher18App.VerificaVoucher.VerificaVoucher {
        
        public VerificaVoucherClient() {
        }
        
        public VerificaVoucherClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VerificaVoucherClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerificaVoucherClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VerificaVoucherClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Italia.Voucher18App.VerificaVoucher.CheckResponse1 Italia.Voucher18App.VerificaVoucher.VerificaVoucher.Check(Italia.Voucher18App.VerificaVoucher.CheckRequest request) {
            return base.Channel.Check(request);
        }
        
        public Italia.Voucher18App.VerificaVoucher.CheckResponse Check(Italia.Voucher18App.VerificaVoucher.Check checkReq) {
            Italia.Voucher18App.VerificaVoucher.CheckRequest inValue = new Italia.Voucher18App.VerificaVoucher.CheckRequest();
            inValue.checkReq = checkReq;
            Italia.Voucher18App.VerificaVoucher.CheckResponse1 retVal = ((Italia.Voucher18App.VerificaVoucher.VerificaVoucher)(this)).Check(inValue);
            return retVal.checkResp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Italia.Voucher18App.VerificaVoucher.CheckResponse1> Italia.Voucher18App.VerificaVoucher.VerificaVoucher.CheckAsync(Italia.Voucher18App.VerificaVoucher.CheckRequest request) {
            return base.Channel.CheckAsync(request);
        }
        
        public System.Threading.Tasks.Task<Italia.Voucher18App.VerificaVoucher.CheckResponse1> CheckAsync(Italia.Voucher18App.VerificaVoucher.Check checkReq) {
            Italia.Voucher18App.VerificaVoucher.CheckRequest inValue = new Italia.Voucher18App.VerificaVoucher.CheckRequest();
            inValue.checkReq = checkReq;
            return ((Italia.Voucher18App.VerificaVoucher.VerificaVoucher)(this)).CheckAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Italia.Voucher18App.VerificaVoucher.ConfirmResponse1 Italia.Voucher18App.VerificaVoucher.VerificaVoucher.Confirm(Italia.Voucher18App.VerificaVoucher.ConfirmRequest request) {
            return base.Channel.Confirm(request);
        }
        
        public Italia.Voucher18App.VerificaVoucher.ConfirmResponse Confirm(Italia.Voucher18App.VerificaVoucher.Confirm checkReq) {
            Italia.Voucher18App.VerificaVoucher.ConfirmRequest inValue = new Italia.Voucher18App.VerificaVoucher.ConfirmRequest();
            inValue.checkReq = checkReq;
            Italia.Voucher18App.VerificaVoucher.ConfirmResponse1 retVal = ((Italia.Voucher18App.VerificaVoucher.VerificaVoucher)(this)).Confirm(inValue);
            return retVal.checkResp;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Italia.Voucher18App.VerificaVoucher.ConfirmResponse1> Italia.Voucher18App.VerificaVoucher.VerificaVoucher.ConfirmAsync(Italia.Voucher18App.VerificaVoucher.ConfirmRequest request) {
            return base.Channel.ConfirmAsync(request);
        }
        
        public System.Threading.Tasks.Task<Italia.Voucher18App.VerificaVoucher.ConfirmResponse1> ConfirmAsync(Italia.Voucher18App.VerificaVoucher.Confirm checkReq) {
            Italia.Voucher18App.VerificaVoucher.ConfirmRequest inValue = new Italia.Voucher18App.VerificaVoucher.ConfirmRequest();
            inValue.checkReq = checkReq;
            return ((Italia.Voucher18App.VerificaVoucher.VerificaVoucher)(this)).ConfirmAsync(inValue);
        }
    }
}
